/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vijay.org.visa;

import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import org.vijay.common.AnarTrading;
import org.vijay.common.CurrentWorkingDirectory;
import org.vijay.common.DateCellRenderer;
import org.vijay.common.connection;
import org.vijay.report.ReportView;

/**
 *
 * @author MAC
 */
public class BusinessVisaEntered extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusinessVisaCompleteStatus
     */
    public BusinessVisaEntered() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        viewDbDetails();    
        CurrentWorkingDirectory CWD=new CurrentWorkingDirectory();
        path=CWD.getpath();
    }
    
    public void viewDbDetails()
    {
        connection c=new connection();
        Connection con=c.conn();
        try
        {
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select @i := @i + 1 '"+"SL.NO"+"',tbl_business_visa_appli.businessVisaId '"+"Id"+"',concat(concat(concat(concat(concat(concat(concat(concat(tbl_business_visa_appli.applicantName1,'"+" "+"'),tbl_business_visa_appli.applicantName2),'"+" "+"'),tbl_business_visa_appli.applicantName3),'"+" "+"'),tbl_business_visa_appli.applicantName4),'"+" "+"'),tbl_business_visa_appli.applicantName5)'"+"Name"+"',tbl_business_visa_appli.sex ,tbl_business_visa_appli.nationality,tbl_business_visa_appli.passportNumber'"+"pp.no"+"',tbl_business_visa_appli.passportExpiry '"+"pp.Exp"+"',tbl_business_visa_appli.dateOfBirth'"+"dob"+"',tbl_business_visa_details.visaNumber,tbl_business_visa_entrydate.entryDate,tbl_business_visa_entrydate.expiryDate,tbl_business_visa_appli.status from anar.tbl_business_visa_details INNER JOIN anar.tbl_business_visa_appli ON (tbl_business_visa_details.businessVisaId = tbl_business_visa_appli.businessVisaId) INNER JOIN anar.tbl_business_visa_entrydate ON (tbl_business_visa_entrydate.businessVisaId = tbl_business_visa_appli.businessVisaId),(SELECT @i := 0) temp where tbl_business_visa_appli.status='Entered to the country' order by tbl_business_visa_appli.businessVisaId");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoCreateRowSorter(true);
            //Sl No
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            //Business Id
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
            //Name
            jTable1.getColumnModel().getColumn(2).setMaxWidth(350);
            //sex
            jTable1.getColumnModel().getColumn(3).setMaxWidth(30);
            //Nationality
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            //PP Number
            jTable1.getColumnModel().getColumn(5).setMaxWidth(80);
            //PP.Expiry
            jTable1.getColumnModel().getColumn(6).setMaxWidth(80);
            //dob
            jTable1.getColumnModel().getColumn(7).setMaxWidth(80);
            //visaNumber
            jTable1.getColumnModel().getColumn(8).setMaxWidth(100);
            //Entry Date
            jTable1.getColumnModel().getColumn(9).setMaxWidth(80);
            //Expiry Date
            jTable1.getColumnModel().getColumn(10).setMaxWidth(80);
            //Status
            jTable1.getColumnModel().getColumn(11).setMaxWidth(150);
            
            jTable1.getColumnModel().getColumn(6).setCellRenderer(new DateCellRenderer());
            jTable1.getColumnModel().getColumn(7).setCellRenderer(new DateCellRenderer());
            jTable1.getColumnModel().getColumn(9).setCellRenderer(new DateCellRenderer());
            jTable1.getColumnModel().getColumn(10).setCellRenderer(new DateCellRenderer());
            con.close();


        }
        catch(Exception e)
        {

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnApproved = new javax.swing.JButton();

        setClosable(true);
        setTitle("Business Visa- Entered to the Country Details");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entered To Country", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnApproved.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnApproved.setText("Print Details");
        btnApproved.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApproved.setContentAreaFilled(false);
        btnApproved.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApproved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApproved)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApproved)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    private void btnApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedActionPerformed
        // TODO add your handling code here:
        HashMap para=new HashMap();
        ReportView re=new ReportView(path.concat("\\lib\\Reports\\Anar\\BusinessVisa\\EnteredDetails.jasper"));
        re.setVisible(true);

        
    }//GEN-LAST:event_btnApprovedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproved;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    String  path;
}
