package org.vijay.common;



//import com.nilo.plaf.nimrod.NimRODLookAndFeel;
//import com.nilo.plaf.nimrod.NimRODTheme;
import org.vijay.contractEmployee.AdvancedContractEmployeeSearch;
import org.vijay.contractEmployee.ContractEmployeeDetails;
import org.vijay.holiday.HolidayDetails;
import org.vijay.payment.AdvancePayment;
import org.vijay.payment.paymentVoucher;
import org.vijay.invoice.InvoiceReceived;
import org.vijay.invoice.InvoiceEntry;
import org.vijay.receipt.ReceiptVoucher;
import org.vijay.employee.AdvancedEmployeeSearch;
import org.vijay.employee.LabourDetails;
import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author vijay
 */
public class AnarTrading extends javax.swing.JFrame {

    /** Creates new form InventryMdi */
    public AnarTrading() {
        initComponents();
        jToolBar1.setVisible(false);
        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnEmployee = new javax.swing.JButton();
        btnAdvanced = new javax.swing.JButton();
        btnReceiptVoucher = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnServerBkp = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnAccount1 = new javax.swing.JButton();
        btnAccount2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuWindow = new javax.swing.JMenu();
        menuFile = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        menuCourse = new javax.swing.JMenu();
        menuItemLabourDetails = new javax.swing.JMenuItem();
        menuItemContractEmployee = new javax.swing.JMenuItem();
        menuItemHoliday = new javax.swing.JMenuItem();
        menuItemAdvancePayment = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemInvoice = new javax.swing.JMenuItem();
        menuItemInvoiceReceived = new javax.swing.JMenuItem();
        menuTransaction = new javax.swing.JMenu();
        menuItemReceiptVoucher = new javax.swing.JMenuItem();
        menuItemPaymentVoucher = new javax.swing.JMenuItem();
        menuHelp1 = new javax.swing.JMenu();
        menuHelp2 = new javax.swing.JMenu();
        menuItemSearchEmployee = new javax.swing.JMenuItem();
        menuItemSearchConEmployee = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menu = new javax.swing.JMenu();

        jToolBar2.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(25, 30, 39));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("Tool Bar");
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolBar1.setMargin(new java.awt.Insets(0, 20, 0, -1));
        jToolBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToolBar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToolBar1MouseExited(evt);
            }
        });

        btnEmployee.setBackground(new java.awt.Color(255, 255, 255));
        btnEmployee.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon.png"))); // NOI18N
        btnEmployee.setText("Employee");
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.setFocusable(false);
        btnEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmployee.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnEmployee.setMaximumSize(new java.awt.Dimension(90, 93));
        btnEmployee.setMinimumSize(new java.awt.Dimension(71, 93));
        btnEmployee.setPreferredSize(new java.awt.Dimension(71, 93));
        btnEmployee.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon1.png"))); // NOI18N
        btnEmployee.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/billingIcon1.png"))); // NOI18N
        btnEmployee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseEntered(evt);
            }
        });
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEmployee);

        btnAdvanced.setBackground(new java.awt.Color(255, 255, 255));
        btnAdvanced.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnAdvanced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon.png"))); // NOI18N
        btnAdvanced.setText("Adavanced");
        btnAdvanced.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdvanced.setFocusable(false);
        btnAdvanced.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdvanced.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnAdvanced.setMaximumSize(new java.awt.Dimension(90, 93));
        btnAdvanced.setMinimumSize(new java.awt.Dimension(71, 93));
        btnAdvanced.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon1.png"))); // NOI18N
        btnAdvanced.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/purchaseIcon1.png"))); // NOI18N
        btnAdvanced.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdvanced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdvancedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdvancedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdvancedMouseExited(evt);
            }
        });
        btnAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdvancedActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdvanced);

        btnReceiptVoucher.setBackground(new java.awt.Color(255, 255, 255));
        btnReceiptVoucher.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnReceiptVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon.png"))); // NOI18N
        btnReceiptVoucher.setText("Receipt");
        btnReceiptVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReceiptVoucher.setFocusable(false);
        btnReceiptVoucher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReceiptVoucher.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnReceiptVoucher.setMaximumSize(new java.awt.Dimension(90, 93));
        btnReceiptVoucher.setMinimumSize(new java.awt.Dimension(71, 93));
        btnReceiptVoucher.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon1.png"))); // NOI18N
        btnReceiptVoucher.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/SearchIcon1.png"))); // NOI18N
        btnReceiptVoucher.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReceiptVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReceiptVoucherMouseEntered(evt);
            }
        });
        btnReceiptVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptVoucherActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReceiptVoucher);

        btnPayment.setBackground(new java.awt.Color(255, 255, 255));
        btnPayment.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon.png"))); // NOI18N
        btnPayment.setText("Payment");
        btnPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayment.setFocusable(false);
        btnPayment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayment.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnPayment.setMaximumSize(new java.awt.Dimension(90, 93));
        btnPayment.setMinimumSize(new java.awt.Dimension(71, 93));
        btnPayment.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon1.png"))); // NOI18N
        btnPayment.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/StockIcon1.png"))); // NOI18N
        btnPayment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentMouseEntered(evt);
            }
        });
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPayment);

        btnStudent.setBackground(new java.awt.Color(255, 255, 255));
        btnStudent.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/ServiceIcon.png"))); // NOI18N
        btnStudent.setText("5");
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent.setFocusable(false);
        btnStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStudent.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnStudent.setMaximumSize(new java.awt.Dimension(90, 93));
        btnStudent.setMinimumSize(new java.awt.Dimension(71, 93));
        btnStudent.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/ServiceIcon1.png"))); // NOI18N
        btnStudent.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/ServiceIcon1.png"))); // NOI18N
        btnStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentMouseEntered(evt);
            }
        });
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStudent);

        btnExcel.setBackground(new java.awt.Color(255, 255, 255));
        btnExcel.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/ExcelBkpIcon.png"))); // NOI18N
        btnExcel.setText("6");
        btnExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcel.setFocusable(false);
        btnExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcel.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnExcel.setMaximumSize(new java.awt.Dimension(90, 93));
        btnExcel.setMinimumSize(new java.awt.Dimension(71, 93));
        btnExcel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/ExcelBkpIcon1.png"))); // NOI18N
        btnExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcelMouseEntered(evt);
            }
        });
        jToolBar1.add(btnExcel);

        btnServerBkp.setBackground(new java.awt.Color(255, 255, 255));
        btnServerBkp.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnServerBkp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon.png"))); // NOI18N
        btnServerBkp.setText("7");
        btnServerBkp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServerBkp.setFocusable(false);
        btnServerBkp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServerBkp.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnServerBkp.setMaximumSize(new java.awt.Dimension(90, 93));
        btnServerBkp.setMinimumSize(new java.awt.Dimension(71, 93));
        btnServerBkp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon1.png"))); // NOI18N
        btnServerBkp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/serverBkpIcon1.png"))); // NOI18N
        btnServerBkp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServerBkp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServerBkpMouseEntered(evt);
            }
        });
        jToolBar1.add(btnServerBkp);

        btnAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnAccount.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon.png"))); // NOI18N
        btnAccount.setText("8");
        btnAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccount.setFocusable(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnAccount.setMaximumSize(new java.awt.Dimension(90, 93));
        btnAccount.setMinimumSize(new java.awt.Dimension(71, 93));
        btnAccount.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon1.png"))); // NOI18N
        btnAccount.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon1.png"))); // NOI18N
        btnAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccountMouseEntered(evt);
            }
        });
        jToolBar1.add(btnAccount);

        btnAccount1.setBackground(new java.awt.Color(255, 255, 255));
        btnAccount1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon.png"))); // NOI18N
        btnAccount1.setText("9");
        btnAccount1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccount1.setFocusable(false);
        btnAccount1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount1.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnAccount1.setMaximumSize(new java.awt.Dimension(90, 93));
        btnAccount1.setMinimumSize(new java.awt.Dimension(71, 93));
        btnAccount1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon1.png"))); // NOI18N
        btnAccount1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon1.png"))); // NOI18N
        btnAccount1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccount1MouseEntered(evt);
            }
        });
        jToolBar1.add(btnAccount1);

        btnAccount2.setBackground(new java.awt.Color(255, 255, 255));
        btnAccount2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnAccount2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon.png"))); // NOI18N
        btnAccount2.setText("10");
        btnAccount2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccount2.setFocusable(false);
        btnAccount2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount2.setMargin(new java.awt.Insets(2, 5, 0, 5));
        btnAccount2.setMaximumSize(new java.awt.Dimension(90, 93));
        btnAccount2.setMinimumSize(new java.awt.Dimension(71, 93));
        btnAccount2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon1.png"))); // NOI18N
        btnAccount2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/AccountIcon1.png"))); // NOI18N
        btnAccount2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccount2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccount2MouseEntered(evt);
            }
        });
        jToolBar1.add(btnAccount2);

        desktopPane.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 100, 1000);
        desktopPane.add(jSeparator6);
        jSeparator6.setBounds(160, 280, 0, 2);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(190, 945));
        jPanel1.setLayout(null);
        desktopPane.add(jPanel1);
        jPanel1.setBounds(75, -10, 190, 950);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setMargin(new java.awt.Insets(0, 0, 0, 50));

        menuWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/menuIcons/windows.png"))); // NOI18N
        menuWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuWindowMouseExited(evt);
            }
        });
        menuWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWindowActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuWindow);

        menuFile.setForeground(new java.awt.Color(255, 255, 255));
        menuFile.setMnemonic('F');
        menuFile.setText("File");
        menuFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFile.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        menuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFileMouseClicked(evt);
            }
        });

        menuItemExit.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemExit.setMnemonic('E');
        menuItemExit.setText("Exit");
        menuItemExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        menuCourse.setForeground(new java.awt.Color(255, 255, 255));
        menuCourse.setMnemonic('U');
        menuCourse.setText("Tune-Up");
        menuCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCourse.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        menuCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCourseMouseClicked(evt);
            }
        });
        menuCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCourseActionPerformed(evt);
            }
        });

        menuItemLabourDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemLabourDetails.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemLabourDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/menuIcons/company.png"))); // NOI18N
        menuItemLabourDetails.setMnemonic('E');
        menuItemLabourDetails.setText("Employee Entry");
        menuItemLabourDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemLabourDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLabourDetailsActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemLabourDetails);

        menuItemContractEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemContractEmployee.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemContractEmployee.setMnemonic('C');
        menuItemContractEmployee.setText("Contract Employee Entry");
        menuItemContractEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContractEmployeeActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemContractEmployee);

        menuItemHoliday.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemHoliday.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemHoliday.setMnemonic('H');
        menuItemHoliday.setText("Holiday Entry");
        menuItemHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHolidayActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemHoliday);

        menuItemAdvancePayment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemAdvancePayment.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemAdvancePayment.setMnemonic('A');
        menuItemAdvancePayment.setText("Advance Payment Entry");
        menuItemAdvancePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdvancePaymentActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemAdvancePayment);

        jMenu1.setMnemonic('I');
        jMenu1.setText("Invoice");
        jMenu1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N

        menuItemInvoice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemInvoice.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemInvoice.setMnemonic('I');
        menuItemInvoice.setText("Send");
        menuItemInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInvoiceActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInvoice);

        menuItemInvoiceReceived.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemInvoiceReceived.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemInvoiceReceived.setMnemonic('R');
        menuItemInvoiceReceived.setText("Received");
        menuItemInvoiceReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInvoiceReceivedActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInvoiceReceived);

        menuCourse.add(jMenu1);

        jMenuBar1.add(menuCourse);

        menuTransaction.setForeground(new java.awt.Color(255, 255, 255));
        menuTransaction.setMnemonic('T');
        menuTransaction.setText("Transaction");
        menuTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTransaction.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N

        menuItemReceiptVoucher.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemReceiptVoucher.setMnemonic('R');
        menuItemReceiptVoucher.setText("Receipt Voucher");
        menuItemReceiptVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemReceiptVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReceiptVoucherActionPerformed(evt);
            }
        });
        menuTransaction.add(menuItemReceiptVoucher);

        menuItemPaymentVoucher.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemPaymentVoucher.setText("Payment Voucher");
        menuItemPaymentVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPaymentVoucherActionPerformed(evt);
            }
        });
        menuTransaction.add(menuItemPaymentVoucher);

        jMenuBar1.add(menuTransaction);

        menuHelp1.setForeground(new java.awt.Color(255, 255, 255));
        menuHelp1.setMnemonic('S');
        menuHelp1.setText("Search");
        menuHelp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp1.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        menuHelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelp1MouseClicked(evt);
            }
        });
        menuHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelp1ActionPerformed(evt);
            }
        });

        menuHelp2.setMnemonic('A');
        menuHelp2.setText("Advanced");
        menuHelp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuHelp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelp2MouseClicked(evt);
            }
        });
        menuHelp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelp2ActionPerformed(evt);
            }
        });

        menuItemSearchEmployee.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemSearchEmployee.setMnemonic('E');
        menuItemSearchEmployee.setText("Employee");
        menuItemSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchEmployeeActionPerformed(evt);
            }
        });
        menuHelp2.add(menuItemSearchEmployee);

        menuItemSearchConEmployee.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        menuItemSearchConEmployee.setMnemonic('C');
        menuItemSearchConEmployee.setText("Contract Employee");
        menuItemSearchConEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchConEmployeeActionPerformed(evt);
            }
        });
        menuHelp2.add(menuItemSearchConEmployee);

        menuHelp1.add(menuHelp2);

        jMenuBar1.add(menuHelp1);

        menuHelp.setForeground(new java.awt.Color(255, 255, 255));
        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");
        menuHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        menuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelpMouseClicked(evt);
            }
        });
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuHelp);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Exiticon1.png"))); // NOI18N
        menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Exiticon1.png"))); // NOI18N
        menu.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Exiticon1.png"))); // NOI18N
        menu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Exiticon1.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        jMenuBar1.add(Box.createHorizontalGlue());

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdvancedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdvancedMouseEntered

    }//GEN-LAST:event_btnAdvancedMouseEntered

    private void btnAdvancedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdvancedMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdvancedMouseExited

    private void btnAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdvancedActionPerformed

        AdvancedEmployeeSearch av = new AdvancedEmployeeSearch();
        AnarTrading.desktopPane.add(av);
        av.setVisible(true);
        av.show();
//        btnAdvanced.setEnabled(false);
//        menuItemReceiptVoucher.setEnabled(false);
    }//GEN-LAST:event_btnAdvancedActionPerformed

    private void btnAdvancedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdvancedMouseClicked

    }//GEN-LAST:event_btnAdvancedMouseClicked

    private void btnEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseEntered

    }//GEN-LAST:event_btnEmployeeMouseEntered

    private void btnPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseEntered

    }//GEN-LAST:event_btnPaymentMouseEntered

    private void btnStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseEntered

        
    }//GEN-LAST:event_btnStudentMouseEntered

    private void btnExcelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcelMouseEntered

    }//GEN-LAST:event_btnExcelMouseEntered

    private void btnServerBkpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServerBkpMouseEntered

    }//GEN-LAST:event_btnServerBkpMouseEntered

    private void btnAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseEntered

    }//GEN-LAST:event_btnAccountMouseEntered

    private void btnReceiptVoucherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceiptVoucherMouseEntered

    }//GEN-LAST:event_btnReceiptVoucherMouseEntered

    private void menuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileMouseClicked

    }//GEN-LAST:event_menuFileMouseClicked

    private void menuItemReceiptVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReceiptVoucherActionPerformed
        
        ReceiptVoucher RV = new ReceiptVoucher();
        AnarTrading.desktopPane.add(RV);
        RV.setVisible(true);
        btnReceiptVoucher.setEnabled(false);
        AnarTrading.menuItemReceiptVoucher.setEnabled(false);
       
    }//GEN-LAST:event_menuItemReceiptVoucherActionPerformed

    private void menuWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWindowMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuWindowMouseEntered

    private void menuWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWindowMouseExited
        // TODO add your handling code here:
        //jToolBar1.setVisible(false);
    }//GEN-LAST:event_menuWindowMouseExited

    private void jToolBar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolBar1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jToolBar1MouseEntered

    private void jToolBar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolBar1MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jToolBar1MouseExited

    private void menuWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWindowActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_menuWindowActionPerformed

    private void menuWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWindowMouseClicked
        // TODO add your handling code here:
        jToolBar1.setVisible(true);
    }//GEN-LAST:event_menuWindowMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        paymentVoucher PV = new paymentVoucher();
        AnarTrading.desktopPane.add(PV);
        PV.setVisible(true);
        AnarTrading.btnPayment.setEnabled(false);
        AnarTrading.menuItemPaymentVoucher.setEnabled(false);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
         //TODO add your handling code here:
        LabourDetails accession = new LabourDetails();
        AnarTrading.desktopPane.add(accession);
        accession.setVisible(true);
        accession.show();
        btnEmployee.setEnabled(false);
        AnarTrading.menuItemLabourDetails.setEnabled(false);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        // TODO add your handling code here:
//         Help help = new Help();
//         LibraryMdi.desktopPane.add(help);
//         help.setVisible(true);
//         help.show();
//         //btnAccession.setEnabled(false);
//         //LibraryMdi.menuItemAccession.setEnabled(false);
    }//GEN-LAST:event_menuHelpActionPerformed

    private void menuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelpMouseClicked
        // TODO add your handling code here:
//        Help help = new Help();
//         LibraryMdi.desktopPane.add(help);
//         help.setVisible(true);
//         help.show();
    }//GEN-LAST:event_menuHelpMouseClicked

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
//        StudentDetails student = new StudentDetails();
//        LibraryMdi.desktopPane.add(student);
//        student.setVisible(true);
//        student.show();
//        btnStudent.setEnabled(false);
//        menuItemStudent.setEnabled(false);
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnAccount1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccount1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccount1MouseEntered

    private void btnAccount2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccount2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccount2MouseEntered

    private void btnReceiptVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptVoucherActionPerformed
        // TODO add your handling code here:
        ReceiptVoucher RV = new ReceiptVoucher();
        AnarTrading.desktopPane.add(RV);
        RV.setVisible(true);
        btnReceiptVoucher.setEnabled(false);
        AnarTrading.menuItemReceiptVoucher.setEnabled(false);
    }//GEN-LAST:event_btnReceiptVoucherActionPerformed

    private void menuItemPaymentVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPaymentVoucherActionPerformed
        // TODO add your handling code here:
        paymentVoucher PV = new paymentVoucher();
        AnarTrading.desktopPane.add(PV);
        PV.setVisible(true);
        AnarTrading.btnPayment.setEnabled(false);
        AnarTrading.menuItemPaymentVoucher.setEnabled(false);
    }//GEN-LAST:event_menuItemPaymentVoucherActionPerformed

    private void menuHelp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp1MouseClicked

    private void menuHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp1ActionPerformed

    private void menuItemSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchEmployeeActionPerformed
        // TODO add your handling code here:
        AdvancedEmployeeSearch AE = new AdvancedEmployeeSearch();
        AnarTrading.desktopPane.add(AE);
        AE.setVisible(true);
        AnarTrading.menuItemSearchEmployee.setEnabled(false);
    }//GEN-LAST:event_menuItemSearchEmployeeActionPerformed

    private void menuHelp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelp2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp2MouseClicked

    private void menuHelp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp2ActionPerformed

    private void menuItemSearchConEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchConEmployeeActionPerformed
        // TODO add your handling code here:
        AdvancedContractEmployeeSearch ACE = new AdvancedContractEmployeeSearch();
        AnarTrading.desktopPane.add(ACE);
        ACE.setVisible(true);
        AnarTrading.menuItemSearchConEmployee.setEnabled(false);
    }//GEN-LAST:event_menuItemSearchConEmployeeActionPerformed

    private void menuCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCourseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuCourseActionPerformed

    private void menuCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCourseMouseClicked

    }//GEN-LAST:event_menuCourseMouseClicked

    private void menuItemInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInvoiceActionPerformed
        // TODO add your handling code here:
        InvoiceEntry IE = new InvoiceEntry();
        AnarTrading.desktopPane.add(IE);
        IE.setVisible(true);
        AnarTrading.menuItemInvoice.setEnabled(false);
    }//GEN-LAST:event_menuItemInvoiceActionPerformed

    private void menuItemAdvancePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdvancePaymentActionPerformed
        // TODO add your handling code here:
        AdvancePayment advance = new AdvancePayment();
        AnarTrading.desktopPane.add(advance);
        advance.setVisible(true);
        advance.show();
        AnarTrading.menuItemAdvancePayment.setEnabled(false);
    }//GEN-LAST:event_menuItemAdvancePaymentActionPerformed

    private void menuItemHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHolidayActionPerformed
        // TODO add your handling code here:
        HolidayDetails holiday = new HolidayDetails();
        AnarTrading.desktopPane.add(holiday);
        holiday.setVisible(true);
        holiday.show();
        AnarTrading.menuItemHoliday.setEnabled(false);
    }//GEN-LAST:event_menuItemHolidayActionPerformed

    private void menuItemContractEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContractEmployeeActionPerformed
        // TODO add your handling code here:
        ContractEmployeeDetails CE = new ContractEmployeeDetails();
        AnarTrading.desktopPane.add(CE);
        CE.setVisible(true);
        AnarTrading.menuItemContractEmployee.setEnabled(false);
    }//GEN-LAST:event_menuItemContractEmployeeActionPerformed

    private void menuItemLabourDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLabourDetailsActionPerformed

        LabourDetails labour = new LabourDetails();
        AnarTrading.desktopPane.add(labour);
        labour.setVisible(true);
        labour.show();
        btnEmployee.setEnabled(false);
    }//GEN-LAST:event_menuItemLabourDetailsActionPerformed

    private void menuItemInvoiceReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInvoiceReceivedActionPerformed
        // TODO add your handling code here:
        InvoiceReceived IR = new InvoiceReceived();
        AnarTrading.desktopPane.add(IR);
        IR.setVisible(true);
        IR.show();
    }//GEN-LAST:event_menuItemInvoiceReceivedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            //javax.swing.UIManager.setLookAndFeel(new com.nilo.plaf.nimrod.NimRODLookAndFeel());
            NimRODTheme nt = new NimRODTheme();
            
            //window right side shade
            nt.setPrimary1(new Color(191,191,191));
            //slection color
            nt.setPrimary2(new Color(0,150,179));//94, 94, 202
            //window left side shade
            nt.setPrimary3(new Color(191,191, 191));
            //Border Color for Button,Table Header
            nt.setSecondary1(new Color(155,152,100));//25, 30, 39
            //Border Color for Panel,Table Data
            nt.setSecondary2(new Color(165, 162, 110));
            //BackGround color
            nt.setSecondary3(new Color(210, 218, 221));
            
            nt.setWhite(new Color(208, 203, 150));
            nt.setBlack(new Color(0, 0, 0));
            nt.setOpacity(195);
            nt.setFrameOpacity(180);


            NimRODLookAndFeel NimRODLF = new NimRODLookAndFeel();
            NimRODLF.setCurrentTheme(nt);
            UIManager.setLookAndFeel(NimRODLF);
        } 
        catch (UnsupportedLookAndFeelException ex) 
        {
            Logger.getLogger(AnarTrading.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AnarTrading().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnAccount1;
    private javax.swing.JButton btnAccount2;
    public static javax.swing.JButton btnAdvanced;
    public static javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExcel;
    public static javax.swing.JButton btnPayment;
    public static javax.swing.JButton btnReceiptVoucher;
    private javax.swing.JButton btnServerBkp;
    public static javax.swing.JButton btnStudent;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menuCourse;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuHelp1;
    private javax.swing.JMenu menuHelp2;
    public static javax.swing.JMenuItem menuItemAdvancePayment;
    public static javax.swing.JMenuItem menuItemContractEmployee;
    private javax.swing.JMenuItem menuItemExit;
    public static javax.swing.JMenuItem menuItemHoliday;
    public static javax.swing.JMenuItem menuItemInvoice;
    public static javax.swing.JMenuItem menuItemInvoiceReceived;
    public static javax.swing.JMenuItem menuItemLabourDetails;
    public static javax.swing.JMenuItem menuItemPaymentVoucher;
    public static javax.swing.JMenuItem menuItemReceiptVoucher;
    public static javax.swing.JMenuItem menuItemSearchConEmployee;
    public static javax.swing.JMenuItem menuItemSearchEmployee;
    private javax.swing.JMenu menuTransaction;
    private javax.swing.JMenu menuWindow;
    // End of variables declaration//GEN-END:variables
    public static int jtableValueCount;
}
