package org.vijay.common;



//import com.nilo.plaf.nimrod.NimRODLookAndFeel;
//import com.nilo.plaf.nimrod.NimRODTheme;
import org.vijay.holiday.HolidayDetails;
import org.vijay.payment.SalaryDeductions;
import org.vijay.payment.paymentVoucher;
import org.vijay.invoice.InvoiceReceived;
import org.vijay.invoice.InvoiceEntry;
import org.vijay.receipt.ReceiptVoucher;
import org.vijay.employee.AdvancedEmployeeSearch;
import org.vijay.employee.LabourDetails;
import com.vijay.reports.SiteWorkingHr;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.vijay.bank.AnarCBQ;
import org.vijay.bank.AnarCBQsearch;
import org.vijay.bank.FixtureCBQ;
import org.vijay.bank.FixtureCBQsearch;
import org.vijay.bank.FixtureDoha;
import org.vijay.bank.FixtureDohaSearch;
import org.vijay.cheque.AdvancedChequeSearch;
import org.vijay.cheque.ChequePrinting;
import org.vijay.contractEmployee.ConEmployeeTimeSheet;
import org.vijay.contractEmployee.ConEmployeesSearch;
import org.vijay.contractEmployee.ConTimeSheetSearch;
import org.vijay.contractEmployee.ContractLabourDetails;
import org.vijay.employee.PPExpiryList;
import org.vijay.employee.RPExpiryList;
import org.vijay.invoice.AdvancedInvoiceReceivedSearch;
import org.vijay.invoice.AdvancedInvoiceSearch;
import org.vijay.invoice.InvoiceNew;
import org.vijay.invoice.InvoiceviewTemplate;
import org.vijay.petty.PettyCashEntry;
import org.vijay.petty.pettySearch;
import org.vijay.stock.SafetyStock;
import vijay.org.visa.BusinessVisa;

/**
 *
 * @author vijay
 */
public class AnarTrading extends javax.swing.JFrame {

    /** Creates new form InventryMdi */
    public AnarTrading() {
        initComponents();
        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnNewEmployee = new javax.swing.JButton();
        btnSearchEmployee = new javax.swing.JButton();
        btnRpExpiry = new javax.swing.JButton();
        btnPpExpiry = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnNewContractEmployee = new javax.swing.JButton();
        btnNewContractEmployee1 = new javax.swing.JButton();
        btnTimeSheet = new javax.swing.JButton();
        btnTimeSheetSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnInvoiceSend = new javax.swing.JButton();
        btnInvoiceReceived = new javax.swing.JButton();
        btnInvoiceSendRearch = new javax.swing.JButton();
        btnInvoiceReceivedSearch = new javax.swing.JButton();
        btnInvoiceTemplate = new javax.swing.JButton();
        btnViewInvoice = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCheque = new javax.swing.JButton();
        btnChequeSearch = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnStock = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnAnarCBQentry = new javax.swing.JButton();
        btnAnarCbqSearch = new javax.swing.JButton();
        btnFixtureCBQentry = new javax.swing.JButton();
        btnFixtureCbqSearch = new javax.swing.JButton();
        btnFixDoha = new javax.swing.JButton();
        btnFixtureDohaSearch = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnPettyCash = new javax.swing.JButton();
        btnPettySearch = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnBusinessApp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuItemNewInvoice = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuCourse = new javax.swing.JMenu();
        menuItemLabourDetails = new javax.swing.JMenuItem();
        menuItemContractEmployee = new javax.swing.JMenuItem();
        menuItemHoliday = new javax.swing.JMenuItem();
        menuItemAdvancePayment = new javax.swing.JMenuItem();
        menuItemSiteWorkingHr = new javax.swing.JMenuItem();
        menuItemChequePrinting = new javax.swing.JMenuItem();
        menuTransaction = new javax.swing.JMenu();
        menuItemReceiptVoucher = new javax.swing.JMenuItem();
        menuItemPaymentVoucher = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemInvoice = new javax.swing.JMenuItem();
        menuItemInvoiceReceived = new javax.swing.JMenuItem();
        menuHelp1 = new javax.swing.JMenu();
        menuHelp2 = new javax.swing.JMenu();
        menuItemSearchEmployee = new javax.swing.JMenuItem();
        menuItemSearchConEmployee = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemCalender = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fixture International");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout desktopPane1Layout = new javax.swing.GroupLayout(desktopPane1);
        desktopPane1.setLayout(desktopPane1Layout);
        desktopPane1Layout.setHorizontalGroup(
            desktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPane1Layout.setVerticalGroup(
            desktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1139, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jTabbedPane1.setBackground(new java.awt.Color(51, 204, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btnNewEmployee.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnNewEmployee.setText("New_Employee");
        btnNewEmployee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewEmployee.setContentAreaFilled(false);
        btnNewEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmployeeActionPerformed(evt);
            }
        });

        btnSearchEmployee.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSearchEmployee.setText("Search");
        btnSearchEmployee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchEmployee.setContentAreaFilled(false);
        btnSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmployeeActionPerformed(evt);
            }
        });

        btnRpExpiry.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRpExpiry.setText("RP_Expiry_List");
        btnRpExpiry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRpExpiry.setContentAreaFilled(false);
        btnRpExpiry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRpExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRpExpiryActionPerformed(evt);
            }
        });

        btnPpExpiry.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPpExpiry.setText("PP_Expiry_List");
        btnPpExpiry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPpExpiry.setContentAreaFilled(false);
        btnPpExpiry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPpExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPpExpiryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnNewEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRpExpiry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPpExpiry)
                .addGap(0, 1034, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearchEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNewEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRpExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(btnPpExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Employee", jPanel3);

        btnNewContractEmployee.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnNewContractEmployee.setText("New_Employee");
        btnNewContractEmployee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewContractEmployee.setContentAreaFilled(false);
        btnNewContractEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewContractEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewContractEmployeeActionPerformed(evt);
            }
        });

        btnNewContractEmployee1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnNewContractEmployee1.setText("Search");
        btnNewContractEmployee1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewContractEmployee1.setContentAreaFilled(false);
        btnNewContractEmployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewContractEmployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewContractEmployee1ActionPerformed(evt);
            }
        });

        btnTimeSheet.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTimeSheet.setText("Time_Sheet");
        btnTimeSheet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTimeSheet.setContentAreaFilled(false);
        btnTimeSheet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimeSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeSheetActionPerformed(evt);
            }
        });

        btnTimeSheetSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnTimeSheetSearch.setText("Time_Sheet_Search");
        btnTimeSheetSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTimeSheetSearch.setContentAreaFilled(false);
        btnTimeSheetSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimeSheetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeSheetSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnNewContractEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewContractEmployee1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimeSheet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimeSheetSearch)
                .addGap(0, 1006, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNewContractEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(btnNewContractEmployee1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimeSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTimeSheetSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Contract Employee", jPanel4);

        btnInvoiceSend.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnInvoiceSend.setText("Send");
        btnInvoiceSend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInvoiceSend.setContentAreaFilled(false);
        btnInvoiceSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvoiceSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceSendActionPerformed(evt);
            }
        });

        btnInvoiceReceived.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnInvoiceReceived.setText("Received");
        btnInvoiceReceived.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInvoiceReceived.setContentAreaFilled(false);
        btnInvoiceReceived.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvoiceReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceReceivedActionPerformed(evt);
            }
        });

        btnInvoiceSendRearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnInvoiceSendRearch.setText("Search");
        btnInvoiceSendRearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInvoiceSendRearch.setContentAreaFilled(false);
        btnInvoiceSendRearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvoiceSendRearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceSendRearchActionPerformed(evt);
            }
        });

        btnInvoiceReceivedSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnInvoiceReceivedSearch.setText("Search");
        btnInvoiceReceivedSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInvoiceReceivedSearch.setContentAreaFilled(false);
        btnInvoiceReceivedSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvoiceReceivedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceReceivedSearchActionPerformed(evt);
            }
        });

        btnInvoiceTemplate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnInvoiceTemplate.setText("New Invoice");
        btnInvoiceTemplate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInvoiceTemplate.setContentAreaFilled(false);
        btnInvoiceTemplate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvoiceTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceTemplateActionPerformed(evt);
            }
        });

        btnViewInvoice.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnViewInvoice.setText("View Invoice");
        btnViewInvoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewInvoice.setContentAreaFilled(false);
        btnViewInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnInvoiceSend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvoiceSendRearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvoiceReceived)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvoiceReceivedSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 978, Short.MAX_VALUE)
                .addComponent(btnInvoiceTemplate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewInvoice))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInvoiceSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInvoiceSendRearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInvoiceReceived, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(btnInvoiceReceivedSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInvoiceTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnViewInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Invoice", jPanel1);

        btnCheque.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCheque.setText("New");
        btnCheque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheque.setContentAreaFilled(false);
        btnCheque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChequeActionPerformed(evt);
            }
        });

        btnChequeSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnChequeSearch.setText("Search");
        btnChequeSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChequeSearch.setContentAreaFilled(false);
        btnChequeSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChequeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChequeSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnCheque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChequeSearch)
                .addGap(0, 1280, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnChequeSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cheque", jPanel2);

        btnStock.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnStock.setText("Stock");
        btnStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStock.setContentAreaFilled(false);
        btnStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnStock)
                .addGap(0, 1327, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stock", jPanel5);

        btnAnarCBQentry.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAnarCBQentry.setText("Anar_CBQ_Entry");
        btnAnarCBQentry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnarCBQentry.setContentAreaFilled(false);
        btnAnarCBQentry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnarCBQentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnarCBQentryActionPerformed(evt);
            }
        });

        btnAnarCbqSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAnarCbqSearch.setText("Anar_CBQ_Date_Wise_Search");
        btnAnarCbqSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnarCbqSearch.setContentAreaFilled(false);
        btnAnarCbqSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnarCbqSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnarCbqSearchActionPerformed(evt);
            }
        });

        btnFixtureCBQentry.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnFixtureCBQentry.setText("Fixture_CBQ_Entry");
        btnFixtureCBQentry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFixtureCBQentry.setContentAreaFilled(false);
        btnFixtureCBQentry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFixtureCBQentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixtureCBQentryActionPerformed(evt);
            }
        });

        btnFixtureCbqSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnFixtureCbqSearch.setText("Fixture_CBQ_Date_Wise_Search");
        btnFixtureCbqSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFixtureCbqSearch.setContentAreaFilled(false);
        btnFixtureCbqSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFixtureCbqSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixtureCbqSearchActionPerformed(evt);
            }
        });

        btnFixDoha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnFixDoha.setText("Fixture_DOHA_Entry");
        btnFixDoha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFixDoha.setContentAreaFilled(false);
        btnFixDoha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFixDoha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixDohaActionPerformed(evt);
            }
        });

        btnFixtureDohaSearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnFixtureDohaSearch.setText("Fixture_DOHA_Date_Wise_Search");
        btnFixtureDohaSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFixtureDohaSearch.setContentAreaFilled(false);
        btnFixtureDohaSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFixtureDohaSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixtureDohaSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnAnarCBQentry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFixtureCBQentry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFixDoha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addComponent(btnAnarCbqSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFixtureCbqSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFixtureDohaSearch)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAnarCBQentry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFixtureCBQentry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFixDoha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAnarCbqSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnFixtureCbqSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnFixtureDohaSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Bank Status", jPanel6);

        btnPettyCash.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPettyCash.setText("Petty_Cash_Entry");
        btnPettyCash.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPettyCash.setContentAreaFilled(false);
        btnPettyCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPettyCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPettyCashActionPerformed(evt);
            }
        });

        btnPettySearch.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnPettySearch.setText("Date_Wise_Search");
        btnPettySearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPettySearch.setContentAreaFilled(false);
        btnPettySearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPettySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPettySearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnPettyCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPettySearch)
                .addGap(0, 1136, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPettyCash, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(btnPettySearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Petty Status", jPanel7);

        btnBusinessApp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBusinessApp.setText("Application");
        btnBusinessApp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBusinessApp.setContentAreaFilled(false);
        btnBusinessApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusinessApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusinessAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnBusinessApp)
                .addGap(0, 1291, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBusinessApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Business Visa", jPanel8);

        jToolBar1.add(jTabbedPane1);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setMargin(new java.awt.Insets(0, 0, 0, 50));

        menuFile.setMnemonic('F');
        menuFile.setText("File");
        menuFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFile.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFileMouseClicked(evt);
            }
        });

        jMenu3.setText("New");

        menuItemNewInvoice.setText("Invoioce");
        menuItemNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewInvoiceActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemNewInvoice);

        menuFile.add(jMenu3);

        menuItemExit.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemExit.setMnemonic('E');
        menuItemExit.setText("Exit");
        menuItemExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        menuCourse.setMnemonic('U');
        menuCourse.setText("Tune-Up");
        menuCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCourse.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCourseMouseClicked(evt);
            }
        });
        menuCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCourseActionPerformed(evt);
            }
        });

        menuItemLabourDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemLabourDetails.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemLabourDetails.setMnemonic('E');
        menuItemLabourDetails.setText("Employee Entry");
        menuItemLabourDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemLabourDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLabourDetailsActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemLabourDetails);

        menuItemContractEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemContractEmployee.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemContractEmployee.setMnemonic('C');
        menuItemContractEmployee.setText("Contract Employee Entry");
        menuItemContractEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemContractEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContractEmployeeActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemContractEmployee);

        menuItemHoliday.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemHoliday.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemHoliday.setMnemonic('H');
        menuItemHoliday.setText("Holiday Entry");
        menuItemHoliday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHolidayActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemHoliday);

        menuItemAdvancePayment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemAdvancePayment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemAdvancePayment.setMnemonic('A');
        menuItemAdvancePayment.setText("Advance Payment Entry");
        menuItemAdvancePayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemAdvancePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdvancePaymentActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemAdvancePayment);

        menuItemSiteWorkingHr.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemSiteWorkingHr.setText("Site Working Hr./Invoice Working Hr.");
        menuItemSiteWorkingHr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemSiteWorkingHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSiteWorkingHrActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemSiteWorkingHr);

        menuItemChequePrinting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemChequePrinting.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemChequePrinting.setMnemonic('E');
        menuItemChequePrinting.setText("Cheque Printing");
        menuItemChequePrinting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemChequePrinting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChequePrintingActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemChequePrinting);

        jMenuBar1.add(menuCourse);

        menuTransaction.setMnemonic('T');
        menuTransaction.setText("Transaction");
        menuTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTransaction.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        menuItemReceiptVoucher.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemReceiptVoucher.setMnemonic('R');
        menuItemReceiptVoucher.setText("Receipt Voucher");
        menuItemReceiptVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemReceiptVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReceiptVoucherActionPerformed(evt);
            }
        });
        menuTransaction.add(menuItemReceiptVoucher);

        menuItemPaymentVoucher.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemPaymentVoucher.setText("Payment Voucher");
        menuItemPaymentVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemPaymentVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPaymentVoucherActionPerformed(evt);
            }
        });
        menuTransaction.add(menuItemPaymentVoucher);

        jMenu1.setMnemonic('I');
        jMenu1.setText("Invoice");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        menuItemInvoice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemInvoice.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemInvoice.setMnemonic('I');
        menuItemInvoice.setText("Send");
        menuItemInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInvoiceActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInvoice);

        menuItemInvoiceReceived.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemInvoiceReceived.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemInvoiceReceived.setMnemonic('R');
        menuItemInvoiceReceived.setText("Received");
        menuItemInvoiceReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInvoiceReceivedActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInvoiceReceived);

        menuTransaction.add(jMenu1);

        jMenuBar1.add(menuTransaction);

        menuHelp1.setMnemonic('S');
        menuHelp1.setText("Search");
        menuHelp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuHelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelp1MouseClicked(evt);
            }
        });
        menuHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelp1ActionPerformed(evt);
            }
        });

        menuHelp2.setMnemonic('A');
        menuHelp2.setText("Advanced");
        menuHelp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuHelp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelp2MouseClicked(evt);
            }
        });
        menuHelp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelp2ActionPerformed(evt);
            }
        });

        menuItemSearchEmployee.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemSearchEmployee.setMnemonic('E');
        menuItemSearchEmployee.setText("Employee");
        menuItemSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchEmployeeActionPerformed(evt);
            }
        });
        menuHelp2.add(menuItemSearchEmployee);

        menuItemSearchConEmployee.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuItemSearchConEmployee.setMnemonic('C');
        menuItemSearchConEmployee.setText("Contract Employee");
        menuItemSearchConEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemSearchConEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchConEmployeeActionPerformed(evt);
            }
        });
        menuHelp2.add(menuItemSearchConEmployee);

        menuHelp1.add(menuHelp2);

        jMenuBar1.add(menuHelp1);

        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");
        menuHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelpMouseClicked(evt);
            }
        });
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });

        menuItemCalender.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemCalender.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemCalender.setMnemonic('C');
        menuItemCalender.setText("Calender");
        menuItemCalender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemCalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCalenderActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemCalender);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane1)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileMouseClicked

    }//GEN-LAST:event_menuFileMouseClicked

    private void menuItemReceiptVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReceiptVoucherActionPerformed
        
        ReceiptVoucher RV = new ReceiptVoucher();
        AnarTrading.desktopPane1.add(RV);
        RV.setVisible(true);
    }//GEN-LAST:event_menuItemReceiptVoucherActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseClicked

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        // TODO add your handling code here:
//         Help help = new Help();
//         LibraryMdi.desktopPane.add(help);
//         help.setVisible(true);
//         help.show();
//         //btnAccession.setEnabled(false);
//         //LibraryMdi.menuItemAccession.setEnabled(false);
    }//GEN-LAST:event_menuHelpActionPerformed

    private void menuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelpMouseClicked
        // TODO add your handling code here:
//        Help help = new Help();
//         LibraryMdi.desktopPane.add(help);
//         help.setVisible(true);
//         help.show();
    }//GEN-LAST:event_menuHelpMouseClicked

    private void menuItemPaymentVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPaymentVoucherActionPerformed
        // TODO add your handling code here:
        paymentVoucher PV = new paymentVoucher();
        AnarTrading.desktopPane1.add(PV);
        PV.setVisible(true);
    }//GEN-LAST:event_menuItemPaymentVoucherActionPerformed

    private void menuHelp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp1MouseClicked

    private void menuHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp1ActionPerformed

    private void menuItemSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchEmployeeActionPerformed
        // TODO add your handling code here:
        AdvancedEmployeeSearch AE = new AdvancedEmployeeSearch();
        AnarTrading.desktopPane1.add(AE);
        AE.setVisible(true);
    }//GEN-LAST:event_menuItemSearchEmployeeActionPerformed

    private void menuHelp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelp2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp2MouseClicked

    private void menuHelp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp2ActionPerformed

    private void menuItemSearchConEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchConEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSearchConEmployeeActionPerformed

    private void menuCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCourseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuCourseActionPerformed

    private void menuCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCourseMouseClicked

    }//GEN-LAST:event_menuCourseMouseClicked

    private void menuItemInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInvoiceActionPerformed
        // TODO add your handling code here:
        InvoiceEntry IE = new InvoiceEntry();
        AnarTrading.desktopPane1.add(IE);
        IE.setVisible(true);
    }//GEN-LAST:event_menuItemInvoiceActionPerformed

    private void menuItemAdvancePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdvancePaymentActionPerformed
        // TODO add your handling code here:
        SalaryDeductions advance = new SalaryDeductions();
        AnarTrading.desktopPane1.add(advance);
        advance.setVisible(true);
        advance.show();
    }//GEN-LAST:event_menuItemAdvancePaymentActionPerformed

    private void menuItemHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHolidayActionPerformed
        // TODO add your handling code here:
        HolidayDetails holiday = new HolidayDetails();
        AnarTrading.desktopPane1.add(holiday);
        holiday.setVisible(true);
        holiday.show();
    }//GEN-LAST:event_menuItemHolidayActionPerformed

    private void menuItemContractEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContractEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemContractEmployeeActionPerformed

    private void menuItemLabourDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLabourDetailsActionPerformed

        LabourDetails labour = new LabourDetails();
        AnarTrading.desktopPane1.add(labour);
        labour.setVisible(true);
        labour.show();
    }//GEN-LAST:event_menuItemLabourDetailsActionPerformed

    private void menuItemInvoiceReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInvoiceReceivedActionPerformed
        // TODO add your handling code here:
        InvoiceReceived IR = new InvoiceReceived();
        AnarTrading.desktopPane1.add(IR);
        IR.setVisible(true);
        IR.show();
    }//GEN-LAST:event_menuItemInvoiceReceivedActionPerformed

    private void menuItemSiteWorkingHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSiteWorkingHrActionPerformed
        // TODO add your handling code here:
        SiteWorkingHr SWH=new SiteWorkingHr();
        AnarTrading.desktopPane1.add(SWH);
        SWH.setVisible(true);
    }//GEN-LAST:event_menuItemSiteWorkingHrActionPerformed

    private void menuItemChequePrintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChequePrintingActionPerformed
        // TODO add your handling code here:
        ChequePrinting CP=new ChequePrinting();
        AnarTrading.desktopPane1.add(CP);
        CP.setVisible(true);
    }//GEN-LAST:event_menuItemChequePrintingActionPerformed

    private void menuItemCalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCalenderActionPerformed
        // TODO add your handling code here:
        Calender Cr=new Calender();
        AnarTrading.desktopPane1.add(Cr);
        Cr.setVisible(true);
    }//GEN-LAST:event_menuItemCalenderActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int keyCode = evt.getKeyCode();
        if(keyCode == KeyEvent.VK_ESCAPE)
        {
           int response=JOptionPane.showConfirmDialog(null,"Do you want Exit ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(response==JOptionPane.NO_OPTION)
            {

            }
            else if(response==JOptionPane.YES_OPTION)
            {
                dispose();
            }
            else if(response==JOptionPane.CLOSED_OPTION)
            {

            } 
        }
        
    }//GEN-LAST:event_formKeyPressed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewInvoiceActionPerformed
        // TODO add your handling code here:
        InvoiceNew IN = new InvoiceNew();
        AnarTrading.desktopPane1.add(IN);
        IN.setVisible(true);
        IN.show();
        
    }//GEN-LAST:event_menuItemNewInvoiceActionPerformed

    private void btnNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmployeeActionPerformed
        // TODO add your handling code here:
        LabourDetails labour = new LabourDetails();
        AnarTrading.desktopPane1.add(labour);
        labour.setVisible(true);
        labour.show();
    }//GEN-LAST:event_btnNewEmployeeActionPerformed

    private void btnSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmployeeActionPerformed
        // TODO add your handling code here:
        AdvancedEmployeeSearch AES = new AdvancedEmployeeSearch();
        AnarTrading.desktopPane1.add(AES);
        AES.setVisible(true);
    }//GEN-LAST:event_btnSearchEmployeeActionPerformed

    private void btnInvoiceSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceSendActionPerformed
        // TODO add your handling code here:
        InvoiceEntry IE = new InvoiceEntry();
        AnarTrading.desktopPane1.add(IE);
        IE.setVisible(true);
    }//GEN-LAST:event_btnInvoiceSendActionPerformed

    private void btnInvoiceReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceReceivedActionPerformed
        // TODO add your handling code here:
        InvoiceReceived IR = new InvoiceReceived();
        AnarTrading.desktopPane1.add(IR);
        IR.setVisible(true);
        IR.show();
    }//GEN-LAST:event_btnInvoiceReceivedActionPerformed

    private void btnInvoiceSendRearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceSendRearchActionPerformed
        // TODO add your handling code here:
        AdvancedInvoiceSearch AIS=new AdvancedInvoiceSearch();
        AnarTrading.desktopPane1.add(AIS);
        AIS.setVisible(true);
        AIS.show();
    }//GEN-LAST:event_btnInvoiceSendRearchActionPerformed

    private void btnInvoiceReceivedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceReceivedSearchActionPerformed
        // TODO add your handling code here:
        AdvancedInvoiceReceivedSearch AIRS=new AdvancedInvoiceReceivedSearch();
        AnarTrading.desktopPane1.add(AIRS);
        AIRS.setVisible(true);
        AIRS.show();
    }//GEN-LAST:event_btnInvoiceReceivedSearchActionPerformed

    private void btnChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChequeActionPerformed
        // TODO add your handling code here:
        ChequePrinting CP=new ChequePrinting();
        AnarTrading.desktopPane1.add(CP);
        CP.setVisible(true);
    }//GEN-LAST:event_btnChequeActionPerformed

    private void btnChequeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChequeSearchActionPerformed
        // TODO add your handling code here:
        AdvancedChequeSearch ACS=new AdvancedChequeSearch();
        AnarTrading.desktopPane1.add(ACS);
        ACS.setVisible(true);
        ACS.show();
    }//GEN-LAST:event_btnChequeSearchActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
        SafetyStock SS=new SafetyStock();
        AnarTrading.desktopPane1.add(SS);
        SS.setVisible(true);
        
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnNewContractEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewContractEmployeeActionPerformed
        // TODO add your handling code here:
        ContractLabourDetails CLD=new ContractLabourDetails();
        AnarTrading.desktopPane1.add(CLD);
        
        CLD.setVisible(true);

    }//GEN-LAST:event_btnNewContractEmployeeActionPerformed

    private void btnRpExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRpExpiryActionPerformed
        // TODO add your handling code here:
        RPExpiryList REL=new RPExpiryList();
        AnarTrading.desktopPane1.add(REL);
        REL.setVisible(true);
    }//GEN-LAST:event_btnRpExpiryActionPerformed

    private void btnPpExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPpExpiryActionPerformed
        // TODO add your handling code here:
        PPExpiryList PEL=new PPExpiryList();
        AnarTrading.desktopPane1.add(PEL);
        PEL.setVisible(true);
    }//GEN-LAST:event_btnPpExpiryActionPerformed

    private void btnPettyCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPettyCashActionPerformed
        // TODO add your handling code here:
        PettyCashEntry PE=new PettyCashEntry();
        AnarTrading.desktopPane1.add(PE);
        PE.setVisible(true);
    }//GEN-LAST:event_btnPettyCashActionPerformed

    private void btnPettySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPettySearchActionPerformed
        // TODO add your handling code here:
        pettySearch PS=new pettySearch();
        AnarTrading.desktopPane1.add(PS);
        PS.setVisible(true);
    }//GEN-LAST:event_btnPettySearchActionPerformed

    private void btnAnarCBQentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnarCBQentryActionPerformed
        // TODO add your handling code here:
        AnarCBQ ACBQ=new AnarCBQ();
        AnarTrading.desktopPane1.add(ACBQ);
        ACBQ.setVisible(true);
    }//GEN-LAST:event_btnAnarCBQentryActionPerformed

    private void btnAnarCbqSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnarCbqSearchActionPerformed
        // TODO add your handling code here:
        AnarCBQsearch ACBQSearch=new AnarCBQsearch();
        AnarTrading.desktopPane1.add(ACBQSearch);
        ACBQSearch.setVisible(true);
    }//GEN-LAST:event_btnAnarCbqSearchActionPerformed

    private void btnFixtureCBQentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixtureCBQentryActionPerformed
        // TODO add your handling code here:
        FixtureCBQ FCBQ=new FixtureCBQ();
        AnarTrading.desktopPane1.add(FCBQ);
        FCBQ.setVisible(true);
    }//GEN-LAST:event_btnFixtureCBQentryActionPerformed

    private void btnFixtureCbqSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixtureCbqSearchActionPerformed
        // TODO add your handling code here:
        FixtureCBQsearch FCBQSearch=new FixtureCBQsearch();
        AnarTrading.desktopPane1.add(FCBQSearch);
        FCBQSearch.setVisible(true);
    }//GEN-LAST:event_btnFixtureCbqSearchActionPerformed

    private void btnFixDohaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixDohaActionPerformed
        // TODO add your handling code here:
        FixtureDoha FDOHA=new FixtureDoha();
        AnarTrading.desktopPane1.add(FDOHA);
        FDOHA.setVisible(true);
    }//GEN-LAST:event_btnFixDohaActionPerformed

    private void btnFixtureDohaSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixtureDohaSearchActionPerformed
        // TODO add your handling code here:
        FixtureDohaSearch FDohaSearch=new FixtureDohaSearch();
        AnarTrading.desktopPane1.add(FDohaSearch);
        FDohaSearch.setVisible(true);
    }//GEN-LAST:event_btnFixtureDohaSearchActionPerformed

    private void btnNewContractEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewContractEmployee1ActionPerformed
        // TODO add your handling code here:
        ConEmployeesSearch CES= new ConEmployeesSearch();
        AnarTrading.desktopPane1.add(CES);
        CES.setVisible(true);
                
    }//GEN-LAST:event_btnNewContractEmployee1ActionPerformed

    private void btnTimeSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeSheetActionPerformed
        // TODO add your handling code here:
        ConEmployeeTimeSheet conTimeSheet=new ConEmployeeTimeSheet(null, true);
        conTimeSheet.setVisible(true);
    }//GEN-LAST:event_btnTimeSheetActionPerformed

    private void btnTimeSheetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeSheetSearchActionPerformed
        // TODO add your handling code here:
        ConTimeSheetSearch CTS= new ConTimeSheetSearch();
        AnarTrading.desktopPane1.add(CTS);
        CTS.setVisible(true);
    }//GEN-LAST:event_btnTimeSheetSearchActionPerformed

    private void btnInvoiceTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceTemplateActionPerformed
        // TODO add your handling code here:
        InvoiceNew.trancateTempTable();
        InvoiceNew.trancateMainTempTable();
        InvoiceNew IN= new InvoiceNew();
        AnarTrading.desktopPane1.add(IN);
        IN.setVisible(true);
        btnInvoiceTemplate.setEnabled(false);
        
    }//GEN-LAST:event_btnInvoiceTemplateActionPerformed

    private void btnViewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInvoiceActionPerformed
        // TODO add your handling code here:
        InvoiceviewTemplate IVT= new InvoiceviewTemplate();
        AnarTrading.desktopPane1.add(IVT);
        IVT.setVisible(true);
        btnViewInvoice.setEnabled(false);
    }//GEN-LAST:event_btnViewInvoiceActionPerformed

    private void btnBusinessAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusinessAppActionPerformed
        // TODO add your handling code here:
        BusinessVisa BV=new BusinessVisa();
        AnarTrading.desktopPane1.add(BV);
        BV.setVisible(true);
    }//GEN-LAST:event_btnBusinessAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
try {
  UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

} catch (Exception e) {
  }


//        try {
//            //javax.swing.UIManager.setLookAndFeel(new com.nilo.plaf.nimrod.NimRODLookAndFeel());
//            NimRODTheme nt = new NimRODTheme();
//            
//            //window right side shade
//            nt.setPrimary1(new Color(0,150,179));
//            //slection color
//            nt.setPrimary2(new Color(0,150,179));//94, 94, 202
//            //window left side shade
//            nt.setPrimary3(new Color(0,150,179));
//            //Border Color for Button,Table Header
//            nt.setSecondary1(new Color(155,152,100));//25, 30, 39
//            //Border Color for Panel,Table Data
//            nt.setSecondary2(new Color(165, 162, 110));
//            //BackGround color
//            nt.setSecondary3(new Color(210, 218, 221));
//            
//            nt.setWhite(new Color(208, 203, 150));
//            nt.setBlack(new Color(0, 0, 0));
//            nt.setOpacity(195);
//            nt.setFrameOpacity(255);
//
//
//            NimRODLookAndFeel NimRODLF = new NimRODLookAndFeel();
//            NimRODLF.setCurrentTheme(nt);
//            UIManager.setLookAndFeel(NimRODLF);
//        } 
//        catch (UnsupportedLookAndFeelException ex) 
//        {
//            Logger.getLogger(AnarTrading.class.getName()).log(Level.SEVERE, null, ex);
//        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AnarTrading().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnarCBQentry;
    private javax.swing.JButton btnAnarCbqSearch;
    private javax.swing.JButton btnBusinessApp;
    private javax.swing.JButton btnCheque;
    private javax.swing.JButton btnChequeSearch;
    private javax.swing.JButton btnFixDoha;
    private javax.swing.JButton btnFixtureCBQentry;
    private javax.swing.JButton btnFixtureCbqSearch;
    private javax.swing.JButton btnFixtureDohaSearch;
    private javax.swing.JButton btnInvoiceReceived;
    private javax.swing.JButton btnInvoiceReceivedSearch;
    private javax.swing.JButton btnInvoiceSend;
    private javax.swing.JButton btnInvoiceSendRearch;
    public static javax.swing.JButton btnInvoiceTemplate;
    private javax.swing.JButton btnNewContractEmployee;
    private javax.swing.JButton btnNewContractEmployee1;
    private javax.swing.JButton btnNewEmployee;
    private javax.swing.JButton btnPettyCash;
    private javax.swing.JButton btnPettySearch;
    private javax.swing.JButton btnPpExpiry;
    private javax.swing.JButton btnRpExpiry;
    private javax.swing.JButton btnSearchEmployee;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnTimeSheet;
    private javax.swing.JButton btnTimeSheetSearch;
    public static javax.swing.JButton btnViewInvoice;
    public static javax.swing.JDesktopPane desktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuCourse;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuHelp1;
    private javax.swing.JMenu menuHelp2;
    public static javax.swing.JMenuItem menuItemAdvancePayment;
    public static javax.swing.JMenuItem menuItemCalender;
    public static javax.swing.JMenuItem menuItemChequePrinting;
    public static javax.swing.JMenuItem menuItemContractEmployee;
    private javax.swing.JMenuItem menuItemExit;
    public static javax.swing.JMenuItem menuItemHoliday;
    public static javax.swing.JMenuItem menuItemInvoice;
    public static javax.swing.JMenuItem menuItemInvoiceReceived;
    public static javax.swing.JMenuItem menuItemLabourDetails;
    private javax.swing.JMenuItem menuItemNewInvoice;
    public static javax.swing.JMenuItem menuItemPaymentVoucher;
    public static javax.swing.JMenuItem menuItemReceiptVoucher;
    public static javax.swing.JMenuItem menuItemSearchConEmployee;
    public static javax.swing.JMenuItem menuItemSearchEmployee;
    public static javax.swing.JMenuItem menuItemSiteWorkingHr;
    private javax.swing.JMenu menuTransaction;
    // End of variables declaration//GEN-END:variables
    public static int jtableValueCount;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
}
