package org.vijay.common;



//import com.nilo.plaf.nimrod.NimRODLookAndFeel;
//import com.nilo.plaf.nimrod.NimRODTheme;
import com.alee.laf.WebLookAndFeel;
import org.vijay.contractEmployee.AdvancedContractEmployeeSearch;
import org.vijay.contractEmployee.ContractEmployeeDetails;
import org.vijay.holiday.HolidayDetails;
import org.vijay.payment.SalaryDeductions;
import org.vijay.payment.paymentVoucher;
import org.vijay.invoice.InvoiceReceived;
import org.vijay.invoice.InvoiceEntry;
import org.vijay.receipt.ReceiptVoucher;
import org.vijay.employee.AdvancedEmployeeSearch;
import org.vijay.employee.LabourDetails;
import com.vijay.reports.SiteWorkingHr;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.vijay.cheque.ChequePrinting;

/**
 *
 * @author vijay
 */
public class AnarTrading extends javax.swing.JFrame {

    /** Creates new form InventryMdi */
    public AnarTrading() {
        initComponents();
        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuWindow = new javax.swing.JMenu();
        menuFile = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        menuCourse = new javax.swing.JMenu();
        menuItemLabourDetails = new javax.swing.JMenuItem();
        menuItemContractEmployee = new javax.swing.JMenuItem();
        menuItemHoliday = new javax.swing.JMenuItem();
        menuItemAdvancePayment = new javax.swing.JMenuItem();
        menuItemSiteWorkingHr = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemInvoice = new javax.swing.JMenuItem();
        menuItemInvoiceReceived = new javax.swing.JMenuItem();
        menuItemChequePrinting = new javax.swing.JMenuItem();
        menuTransaction = new javax.swing.JMenu();
        menuItemReceiptVoucher = new javax.swing.JMenuItem();
        menuItemPaymentVoucher = new javax.swing.JMenuItem();
        menuHelp1 = new javax.swing.JMenu();
        menuHelp2 = new javax.swing.JMenu();
        menuItemSearchEmployee = new javax.swing.JMenuItem();
        menuItemSearchConEmployee = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemCalender = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(149, 169, 182));
        desktopPane.add(jSeparator6);
        jSeparator6.setBounds(160, 280, 0, 2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/2.png"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(0, -70, 1300, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/water.png"))); // NOI18N
        desktopPane.add(jLabel2);
        jLabel2.setBounds(0, 355, 1330, 660);

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setMargin(new java.awt.Insets(0, 0, 0, 50));

        menuWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/menuIcons/windows.png"))); // NOI18N
        menuWindow.setContentAreaFilled(false);
        menuWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuWindowMouseExited(evt);
            }
        });
        menuWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWindowActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuWindow);

        menuFile.setMnemonic('F');
        menuFile.setText("File");
        menuFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFile.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFileMouseClicked(evt);
            }
        });

        menuItemExit.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemExit.setMnemonic('E');
        menuItemExit.setText("Exit");
        menuItemExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        menuCourse.setMnemonic('U');
        menuCourse.setText("Tune-Up");
        menuCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCourse.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCourseMouseClicked(evt);
            }
        });
        menuCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCourseActionPerformed(evt);
            }
        });

        menuItemLabourDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemLabourDetails.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemLabourDetails.setMnemonic('E');
        menuItemLabourDetails.setText("Employee Entry");
        menuItemLabourDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemLabourDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLabourDetailsActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemLabourDetails);

        menuItemContractEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemContractEmployee.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemContractEmployee.setMnemonic('C');
        menuItemContractEmployee.setText("Contract Employee Entry");
        menuItemContractEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemContractEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemContractEmployeeActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemContractEmployee);

        menuItemHoliday.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemHoliday.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemHoliday.setMnemonic('H');
        menuItemHoliday.setText("Holiday Entry");
        menuItemHoliday.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemHoliday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHolidayActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemHoliday);

        menuItemAdvancePayment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemAdvancePayment.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemAdvancePayment.setMnemonic('A');
        menuItemAdvancePayment.setText("Advance Payment Entry");
        menuItemAdvancePayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemAdvancePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdvancePaymentActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemAdvancePayment);

        menuItemSiteWorkingHr.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemSiteWorkingHr.setText("Site Working Hr./Invoice Working Hr.");
        menuItemSiteWorkingHr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemSiteWorkingHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSiteWorkingHrActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemSiteWorkingHr);

        jMenu1.setMnemonic('I');
        jMenu1.setText("Invoice");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        menuItemInvoice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemInvoice.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemInvoice.setMnemonic('I');
        menuItemInvoice.setText("Send");
        menuItemInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInvoiceActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInvoice);

        menuItemInvoiceReceived.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemInvoiceReceived.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemInvoiceReceived.setMnemonic('R');
        menuItemInvoiceReceived.setText("Received");
        menuItemInvoiceReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInvoiceReceivedActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemInvoiceReceived);

        menuCourse.add(jMenu1);

        menuItemChequePrinting.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemChequePrinting.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemChequePrinting.setMnemonic('E');
        menuItemChequePrinting.setText("Cheque Printing");
        menuItemChequePrinting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemChequePrinting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChequePrintingActionPerformed(evt);
            }
        });
        menuCourse.add(menuItemChequePrinting);

        jMenuBar1.add(menuCourse);

        menuTransaction.setMnemonic('T');
        menuTransaction.setText("Transaction");
        menuTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTransaction.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        menuItemReceiptVoucher.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemReceiptVoucher.setMnemonic('R');
        menuItemReceiptVoucher.setText("Receipt Voucher");
        menuItemReceiptVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemReceiptVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReceiptVoucherActionPerformed(evt);
            }
        });
        menuTransaction.add(menuItemReceiptVoucher);

        menuItemPaymentVoucher.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemPaymentVoucher.setText("Payment Voucher");
        menuItemPaymentVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemPaymentVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPaymentVoucherActionPerformed(evt);
            }
        });
        menuTransaction.add(menuItemPaymentVoucher);

        jMenuBar1.add(menuTransaction);

        menuHelp1.setMnemonic('S');
        menuHelp1.setText("Search");
        menuHelp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuHelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelp1MouseClicked(evt);
            }
        });
        menuHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelp1ActionPerformed(evt);
            }
        });

        menuHelp2.setMnemonic('A');
        menuHelp2.setText("Advanced");
        menuHelp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuHelp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelp2MouseClicked(evt);
            }
        });
        menuHelp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelp2ActionPerformed(evt);
            }
        });

        menuItemSearchEmployee.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemSearchEmployee.setMnemonic('E');
        menuItemSearchEmployee.setText("Employee");
        menuItemSearchEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchEmployeeActionPerformed(evt);
            }
        });
        menuHelp2.add(menuItemSearchEmployee);

        menuItemSearchConEmployee.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemSearchConEmployee.setMnemonic('C');
        menuItemSearchConEmployee.setText("Contract Employee");
        menuItemSearchConEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemSearchConEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchConEmployeeActionPerformed(evt);
            }
        });
        menuHelp2.add(menuItemSearchConEmployee);

        menuHelp1.add(menuHelp2);

        jMenuBar1.add(menuHelp1);

        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");
        menuHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHelp.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelpMouseClicked(evt);
            }
        });
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });

        menuItemCalender.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuItemCalender.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        menuItemCalender.setMnemonic('C');
        menuItemCalender.setText("Calender");
        menuItemCalender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuItemCalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCalenderActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemCalender);

        jMenuBar1.add(menuHelp);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Exit.png"))); // NOI18N
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileMouseClicked

    }//GEN-LAST:event_menuFileMouseClicked

    private void menuItemReceiptVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReceiptVoucherActionPerformed
        
        ReceiptVoucher RV = new ReceiptVoucher();
        AnarTrading.desktopPane.add(RV);
        RV.setVisible(true);
    }//GEN-LAST:event_menuItemReceiptVoucherActionPerformed

    private void menuWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWindowMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuWindowMouseEntered

    private void menuWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWindowMouseExited
        // TODO add your handling code here:
        //jToolBar1.setVisible(false);
    }//GEN-LAST:event_menuWindowMouseExited

    private void menuWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWindowActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_menuWindowActionPerformed

    private void menuWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuWindowMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuWindowMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseClicked

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        // TODO add your handling code here:
//         Help help = new Help();
//         LibraryMdi.desktopPane.add(help);
//         help.setVisible(true);
//         help.show();
//         //btnAccession.setEnabled(false);
//         //LibraryMdi.menuItemAccession.setEnabled(false);
    }//GEN-LAST:event_menuHelpActionPerformed

    private void menuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelpMouseClicked
        // TODO add your handling code here:
//        Help help = new Help();
//         LibraryMdi.desktopPane.add(help);
//         help.setVisible(true);
//         help.show();
    }//GEN-LAST:event_menuHelpMouseClicked

    private void menuItemPaymentVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPaymentVoucherActionPerformed
        // TODO add your handling code here:
        paymentVoucher PV = new paymentVoucher();
        AnarTrading.desktopPane.add(PV);
        PV.setVisible(true);
    }//GEN-LAST:event_menuItemPaymentVoucherActionPerformed

    private void menuHelp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp1MouseClicked

    private void menuHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp1ActionPerformed

    private void menuItemSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchEmployeeActionPerformed
        // TODO add your handling code here:
        AdvancedEmployeeSearch AE = new AdvancedEmployeeSearch();
        AnarTrading.desktopPane.add(AE);
        AE.setVisible(true);
    }//GEN-LAST:event_menuItemSearchEmployeeActionPerformed

    private void menuHelp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelp2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp2MouseClicked

    private void menuHelp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHelp2ActionPerformed

    private void menuItemSearchConEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchConEmployeeActionPerformed
        // TODO add your handling code here:
        AdvancedContractEmployeeSearch ACE = new AdvancedContractEmployeeSearch();
        AnarTrading.desktopPane.add(ACE);
        ACE.setVisible(true);
    }//GEN-LAST:event_menuItemSearchConEmployeeActionPerformed

    private void menuCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCourseActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuCourseActionPerformed

    private void menuCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCourseMouseClicked

    }//GEN-LAST:event_menuCourseMouseClicked

    private void menuItemInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInvoiceActionPerformed
        // TODO add your handling code here:
        InvoiceEntry IE = new InvoiceEntry();
        AnarTrading.desktopPane.add(IE);
        IE.setVisible(true);
    }//GEN-LAST:event_menuItemInvoiceActionPerformed

    private void menuItemAdvancePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdvancePaymentActionPerformed
        // TODO add your handling code here:
        SalaryDeductions advance = new SalaryDeductions();
        AnarTrading.desktopPane.add(advance);
        advance.setVisible(true);
        advance.show();
    }//GEN-LAST:event_menuItemAdvancePaymentActionPerformed

    private void menuItemHolidayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHolidayActionPerformed
        // TODO add your handling code here:
        HolidayDetails holiday = new HolidayDetails();
        AnarTrading.desktopPane.add(holiday);
        holiday.setVisible(true);
        holiday.show();
    }//GEN-LAST:event_menuItemHolidayActionPerformed

    private void menuItemContractEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemContractEmployeeActionPerformed
        // TODO add your handling code here:
        ContractEmployeeDetails CE = new ContractEmployeeDetails();
        AnarTrading.desktopPane.add(CE);
        CE.setVisible(true);
    }//GEN-LAST:event_menuItemContractEmployeeActionPerformed

    private void menuItemLabourDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLabourDetailsActionPerformed

        LabourDetails labour = new LabourDetails();
        AnarTrading.desktopPane.add(labour);
        labour.setVisible(true);
        labour.show();
    }//GEN-LAST:event_menuItemLabourDetailsActionPerformed

    private void menuItemInvoiceReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInvoiceReceivedActionPerformed
        // TODO add your handling code here:
        InvoiceReceived IR = new InvoiceReceived();
        AnarTrading.desktopPane.add(IR);
        IR.setVisible(true);
        IR.show();
    }//GEN-LAST:event_menuItemInvoiceReceivedActionPerformed

    private void menuItemSiteWorkingHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSiteWorkingHrActionPerformed
        // TODO add your handling code here:
        SiteWorkingHr SWH=new SiteWorkingHr();
        AnarTrading.desktopPane.add(SWH);
        SWH.setVisible(true);
    }//GEN-LAST:event_menuItemSiteWorkingHrActionPerformed

    private void menuItemChequePrintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChequePrintingActionPerformed
        // TODO add your handling code here:
        ChequePrinting CP=new ChequePrinting();
        AnarTrading.desktopPane.add(CP);
        CP.setVisible(true);
    }//GEN-LAST:event_menuItemChequePrintingActionPerformed

    private void menuItemCalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCalenderActionPerformed
        // TODO add your handling code here:
        Calender Cr=new Calender();
        AnarTrading.desktopPane.add(Cr);
        Cr.setVisible(true);
    }//GEN-LAST:event_menuItemCalenderActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int keyCode = evt.getKeyCode();
        if(keyCode == KeyEvent.VK_ESCAPE)
        {
           int response=JOptionPane.showConfirmDialog(null,"Do you want Exit ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(response==JOptionPane.NO_OPTION)
            {

            }
            else if(response==JOptionPane.YES_OPTION)
            {
                dispose();
            }
            else if(response==JOptionPane.CLOSED_OPTION)
            {

            } 
        }
        
    }//GEN-LAST:event_formKeyPressed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
try {
  UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

} catch (Exception e) {
  }


//        try {
//            //javax.swing.UIManager.setLookAndFeel(new com.nilo.plaf.nimrod.NimRODLookAndFeel());
//            NimRODTheme nt = new NimRODTheme();
//            
//            //window right side shade
//            nt.setPrimary1(new Color(0,150,179));
//            //slection color
//            nt.setPrimary2(new Color(0,150,179));//94, 94, 202
//            //window left side shade
//            nt.setPrimary3(new Color(0,150,179));
//            //Border Color for Button,Table Header
//            nt.setSecondary1(new Color(155,152,100));//25, 30, 39
//            //Border Color for Panel,Table Data
//            nt.setSecondary2(new Color(165, 162, 110));
//            //BackGround color
//            nt.setSecondary3(new Color(210, 218, 221));
//            
//            nt.setWhite(new Color(208, 203, 150));
//            nt.setBlack(new Color(0, 0, 0));
//            nt.setOpacity(195);
//            nt.setFrameOpacity(255);
//
//
//            NimRODLookAndFeel NimRODLF = new NimRODLookAndFeel();
//            NimRODLF.setCurrentTheme(nt);
//            UIManager.setLookAndFeel(NimRODLF);
//        } 
//        catch (UnsupportedLookAndFeelException ex) 
//        {
//            Logger.getLogger(AnarTrading.class.getName()).log(Level.SEVERE, null, ex);
//        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AnarTrading().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JMenu menuCourse;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuHelp1;
    private javax.swing.JMenu menuHelp2;
    public static javax.swing.JMenuItem menuItemAdvancePayment;
    public static javax.swing.JMenuItem menuItemCalender;
    public static javax.swing.JMenuItem menuItemChequePrinting;
    public static javax.swing.JMenuItem menuItemContractEmployee;
    private javax.swing.JMenuItem menuItemExit;
    public static javax.swing.JMenuItem menuItemHoliday;
    public static javax.swing.JMenuItem menuItemInvoice;
    public static javax.swing.JMenuItem menuItemInvoiceReceived;
    public static javax.swing.JMenuItem menuItemLabourDetails;
    public static javax.swing.JMenuItem menuItemPaymentVoucher;
    public static javax.swing.JMenuItem menuItemReceiptVoucher;
    public static javax.swing.JMenuItem menuItemSearchConEmployee;
    public static javax.swing.JMenuItem menuItemSearchEmployee;
    public static javax.swing.JMenuItem menuItemSiteWorkingHr;
    private javax.swing.JMenu menuTransaction;
    private javax.swing.JMenu menuWindow;
    // End of variables declaration//GEN-END:variables
    public static int jtableValueCount;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
}
