import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAC
 */
public class InvoiceDocument extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public InvoiceDocument() {
        initComponents();
    }
     public InvoiceDocument(int invoiceId) {
        this.invoiceId=invoiceId;
        initComponents();
        setLocation(middle);
        viewDocuments();
        //viewEmployeeDetails();
        if(lblInvoice.getIcon()==null)
        {
            btnSave.setEnabled(true);
            
        }
        else
        {
            btnSave.setEnabled(false);
        }
        
    }
    public static BufferedImage resize(BufferedImage image, int width, int height) 
    {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
    public void viewDocuments()
    {
        connection c=new connection();
        Connection con=c.conn();
        try
        {

            PreparedStatement ps=con.prepareStatement("select document from tbl_invoicedocument where invoiceId=?");
            ps.setInt(1, invoiceId);
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                invoiceByte=rs.getBytes(1);
                ByteArrayInputStream bisInvoice = new ByteArrayInputStream(invoiceByte);
                try 
                {                    
                    bfImage=ImageIO.read(bisInvoice);
                    resizedImage=resize(bfImage,663,821);
                    imageIcon=new ImageIcon(resizedImage);
                    lblInvoice.setIcon(imageIcon);                             
                } 
                catch(IOException e)
                {
                    
                }
             }
            
        }
        catch(Exception e)
        {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInvoice = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnPassportPic = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPassportUpdate = new javax.swing.JButton();

        setClosable(true);
        setTitle("View Details");

        lblInvoice.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancel.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/CANCEL.PNG"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPassportPic.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnPassportPic.setText("Browse");
        btnPassportPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassportPicActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/MODIFY.PNG"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jLabel6.setText("Invoice Document");

        btnPassportUpdate.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnPassportUpdate.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(btnPassportPic, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(btnPassportUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPassportPic, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPassportUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        AnarTrading.menuItemInvoice.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(lblInvoice.getIcon()==null)
        {
            JOptionPane.showMessageDialog(rootPane,"Please Browse the Documents then press 'Save' button");
            
        }
        else
        {
            try
            {
                connection c=new connection();
                Connection con=c.conn();
                PreparedStatement ps=con.prepareStatement("insert into tbl_invoicedocument(invoiceId,document) values(?,?)");
                ps.setInt(1,invoiceId);
                ps.setBinaryStream(2,finInvoice,lenInvoice);
                int status=ps.executeUpdate();
                if(status>0)
                {
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Error");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,e);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPassportPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassportPicActionPerformed
        // TODO add your handling code here:
        fc.showOpenDialog(this);
        fileInvoice=fc.getSelectedFile();
        pathInvoice=fileInvoice.getAbsolutePath();
        try
        {
            finInvoice=new FileInputStream(fileInvoice);
            lenInvoice=(int)fileInvoice.length();
            bfImage=ImageIO.read(fileInvoice);
            resizedImage=resize(bfImage,663,821);
            imageIcon=new ImageIcon(resizedImage);
            lblInvoice.setIcon(imageIcon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }     
    }//GEN-LAST:event_btnPassportPicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPassportPic;
    private javax.swing.JButton btnPassportUpdate;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblInvoice;
    // End of variables declaration//GEN-END:variables
    byte[] invoiceByte;
    BufferedImage bfImage,resizedImage;
    ImageIcon imageIcon;
    int invoiceId,lenInvoice;
    String pathInvoice;
    File fileInvoice;
    FileInputStream finInvoice;
    JFileChooser fc=new JFileChooser(new File("C:\\Users\\MAC\\Documents\\Scan"));
    Point middle = new Point(100,0);
}
