import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAC
 */
public class viewDocuments extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public viewDocuments() {
        initComponents();
    }
     public viewDocuments(int empId) {
        this.empId=empId;
        initComponents();
        setLocation(middle);
        viewDocuments();
        viewEmployeeDetails();
        if(lblPic.getIcon()==null && lblPassport.getIcon()==null && lblVisa.getIcon()==null)
        {
            btnSave.setEnabled(true);
            
        }
        else
        {
            btnSave.setEnabled(false);
        }
        
    }
    public static BufferedImage resize(BufferedImage image, int width, int height) 
    {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
    public void viewDocuments()
    {
        connection c=new connection();
        Connection con=c.conn();
        try
        {

            PreparedStatement ps=con.prepareStatement("select pic,passportPic,visaPic from tbl_documents where empId=?");
            ps.setInt(1, empId);
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                picByte=rs.getBytes(1);
                passportByte=rs.getBytes(2);
                visaByte=rs.getBytes(3);
                ByteArrayInputStream bisPic = new ByteArrayInputStream(picByte);
                ByteArrayInputStream bisPassport = new ByteArrayInputStream(passportByte);
                ByteArrayInputStream bisVisa = new ByteArrayInputStream(visaByte);
                try 
                {
                    bfImage=ImageIO.read(bisPic);
                    resizedImage=resize(bfImage,450,250);
                    imageIcon=new ImageIcon(resizedImage);
                    lblPic.setIcon(imageIcon);
                    
                    bfImage=ImageIO.read(bisPassport);
                    resizedImage=resize(bfImage,450,550);
                    imageIcon=new ImageIcon(resizedImage);
                    lblPassport.setIcon(imageIcon);
                    
                    bfImage=ImageIO.read(bisVisa);
                    resizedImage=resize(bfImage,450,550);
                    imageIcon=new ImageIcon(resizedImage);
                    lblVisa.setIcon(imageIcon);
                    
                    
                } 
                catch(IOException e)
                {
                    
                }
             }
            
        }
        catch(Exception e)
        {
            
        }
    }
    public void viewEmployeeDetails()
    {
        connection c=new connection();
        Connection con=c.conn();
        try
        {
            int i=0;
            PreparedStatement ps=con.prepareStatement("SELECT empId,empName,nationality,profession,passportNumber,DATE_FORMAT(passportExpiry ,'%d/%b/%Y'),DATE_FORMAT(visaExpiry,'%d/%b/%Y'),idNumber FROM tbl_labourdetails where empId=?");
            ps.setInt(1,empId);
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                lblEmployeeName.setText(rs.getString(2));
                lblPassportNumber.setText(rs.getString(5));
                lblIdnumber.setText(rs.getString(8));
                lblPassportEx.setText(rs.getString(6));
                lblVisaEx.setText(rs.getString(7));
            }
            
        }
        catch(Exception e)
        {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPic = new javax.swing.JLabel();
        lblPassport = new javax.swing.JLabel();
        lblVisa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblPassportNumber = new javax.swing.JLabel();
        lblIdnumber = new javax.swing.JLabel();
        lblPassportEx = new javax.swing.JLabel();
        lblVisaEx = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnBrowsePic = new javax.swing.JButton();
        btnPassportPic = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPicUpdate = new javax.swing.JButton();
        btnVisaUpdate = new javax.swing.JButton();
        btnPassportUpdate = new javax.swing.JButton();

        setClosable(true);
        setTitle("View Details");

        lblPic.setBackground(new java.awt.Color(153, 204, 255));
        lblPic.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPassport.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblVisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Employee Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Passport Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Id Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Passport Ex.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Visa Ex.");

        lblEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPassportNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblIdnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPassportEx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblVisaEx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCancel.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/CANCEL.PNG"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBrowsePic.setText("Browse");
        btnBrowsePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePicActionPerformed(evt);
            }
        });

        btnPassportPic.setText("Browse");
        btnPassportPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassportPicActionPerformed(evt);
            }
        });

        jButton5.setText("Browse");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/MODIFY.PNG"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel6.setText("Passsport Pic");

        jLabel7.setText("Visa Pic");

        btnPicUpdate.setText("Update");

        btnVisaUpdate.setText("Update");

        btnPassportUpdate.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVisaUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPassportEx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                    .addComponent(lblIdnumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPassportNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmployeeName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblVisaEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnPassportUpdate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPassportPic))
                                .addComponent(lblPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPicUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowsePic))
                            .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(lblPassportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIdnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(lblPassportEx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(lblVisaEx, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBrowsePic)
                        .addComponent(btnPicUpdate))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPassportPic)
                    .addComponent(jButton5)
                    .addComponent(btnVisaUpdate)
                    .addComponent(btnPassportUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        AnarTrading.btnEmployee.setEnabled(true);
        AnarTrading.menuItemLabourDetails.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(lblPic.getIcon()==null && lblPassport.getIcon()==null && lblVisa.getIcon()==null)
        {
            JOptionPane.showMessageDialog(rootPane,"Please Browse the Documents then press 'Save' button");
            
        }
        else
        {
            try
            {
                connection c=new connection();
                Connection con=c.conn();
                PreparedStatement ps=con.prepareStatement("insert into tbl_documents(empId,pic,passportPic,visaPic) values(?,?,?,?)");
                ps.setInt(1,empId);
                ps.setBinaryStream(2,finPic,lenPic);
                ps.setBinaryStream(3,finPassport,lenPassport);
                ps.setBinaryStream(4,finVisa,lenVisa);
                int status=ps.executeUpdate();
                if(status>0)
                {
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Error");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,e);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBrowsePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsePicActionPerformed
        // TODO add your handling code here:
        fc.showOpenDialog(this);
        filePic=fc.getSelectedFile();
        pathPic=filePic.getAbsolutePath();
        try
        {
            finPic=new FileInputStream(filePic);
            lenPic=(int)filePic.length();
            bfImage=ImageIO.read(filePic);
            resizedImage=resize(bfImage,450,250);
            imageIcon=new ImageIcon(resizedImage);
            lblPic.setIcon(imageIcon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }     
    }//GEN-LAST:event_btnBrowsePicActionPerformed

    private void btnPassportPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassportPicActionPerformed
        // TODO add your handling code here:
        fc.showOpenDialog(this);
        filePassport=fc.getSelectedFile();
        pathPassport=filePassport.getAbsolutePath();
        try
        {
            finPassport=new FileInputStream(filePassport);
            lenPassport=(int)filePassport.length();
            bfImage=ImageIO.read(filePassport);
            resizedImage=resize(bfImage,450,550);
            imageIcon=new ImageIcon(resizedImage);
            lblPassport.setIcon(imageIcon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }     
    }//GEN-LAST:event_btnPassportPicActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        fc.showOpenDialog(this);
        fileVisa=fc.getSelectedFile();
        pathVisa=fileVisa.getAbsolutePath();
        try
        {
            finVisa=new FileInputStream(fileVisa);
            lenVisa=(int)fileVisa.length();
            bfImage=ImageIO.read(fileVisa);
            resizedImage=resize(bfImage,450,550);
            imageIcon=new ImageIcon(resizedImage);
            lblVisa.setIcon(imageIcon);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }     
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowsePic;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPassportPic;
    private javax.swing.JButton btnPassportUpdate;
    private javax.swing.JButton btnPicUpdate;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnVisaUpdate;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblIdnumber;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblPassportEx;
    private javax.swing.JLabel lblPassportNumber;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblVisa;
    private javax.swing.JLabel lblVisaEx;
    // End of variables declaration//GEN-END:variables
    byte[] picByte,passportByte,visaByte;
    BufferedImage bfImage,resizedImage;
    ImageIcon imageIcon;
    int empId,lenPic,lenPassport,lenVisa;
    String pathPic,pathPassport,pathVisa;
    File filePic,filePassport,fileVisa;
    FileInputStream finPic,finPassport,finVisa;
    JFileChooser fc=new JFileChooser(new File("D:\\Vijay\\Works\\Employees-Optimized"));
    Point middle = new Point(80,0);
}
