/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.vijay.employee;

import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.vijay.common.connection;
import org.vijay.report.ReportView;
import org.vijay.common.CurrentWorkingDirectory;

/**
 *
 * @author MAC
 */
public class ID extends javax.swing.JInternalFrame {

    /**
     * Creates new form PassportDocument
     */
    public ID() {
        initComponents();
    }
    public ID(int empId) {
        this.empId=empId;
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setLocation(middle);
        viewDocuments();
        if(lblPassport.getIcon()==null)
        {
            btnSave.setEnabled(true);
            btnUpdate.setEnabled(false);
        }
        else
        {
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(false);
        }
        
    }
    public static BufferedImage resize(BufferedImage image, int width, int height) 
    {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }
    public void viewDocuments()
    {
        connection c=new connection();
        Connection con=c.conn();
        try
        {

            PreparedStatement ps=con.prepareStatement("select idDocument from tbl_idemployee where empId=?");
            ps.setInt(1, empId);
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                IDByte=rs.getBytes(1);
                ByteArrayInputStream bisPassport = new ByteArrayInputStream(IDByte);
                try 
                { 
                    bfImage=ImageIO.read(bisPassport);
                    resizedImage=resize(bfImage,400,555);
                    imageIcon=new ImageIcon(resizedImage);
                    lblPassport.setIcon(imageIcon);
                    
                } 
                catch(IOException e)
                {
                    
                }
             }
            
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPassport = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnBrowse = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setClosable(true);
        setTitle("ID");

        lblPassport.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnBrowse.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/SEARCH.PNG"))); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBrowse);

        btnSave.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/SAVE.PNG"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnUpdate.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/MODIFY.PNG"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUpdate);

        btnPrint.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/view.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        fc.showOpenDialog(this);
        fileID=fc.getSelectedFile();
        pathID=fileID.getAbsolutePath();
        try
        {
            finID=new FileInputStream(fileID);
            lenID=(int)fileID.length();
            bfImage=ImageIO.read(fileID);
            resizedImage=resize(bfImage,400,555);
            imageIcon=new ImageIcon(resizedImage);
            lblPassport.setIcon(imageIcon);
            if(imageIcon==null)
            {
                btnUpdate.setEnabled(false);
            }
            else
            {
                btnUpdate.setEnabled(true);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(lblPassport.getIcon()==null)
        {
            JOptionPane.showMessageDialog(rootPane,"Please Browse the RP then press 'Save' button");
            
        }
        else
        {
            try
            {
                connection c=new connection();
                Connection con=c.conn();
                PreparedStatement ps=con.prepareStatement("insert into tbl_idemployee(empId,idDocument) values(?,?)");
                ps.setInt(1,empId);
                ps.setBinaryStream(2,finID,lenID);
                int status=ps.executeUpdate();
                if(status>0)
                {
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Error");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,e);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if(lblPassport.getIcon()==null)
        {
            JOptionPane.showMessageDialog(rootPane,"Please Browse the new RP then press 'Update' button");
            
        }
        else
        {
            try
            {
                connection c=new connection();
                Connection con=c.conn();
                PreparedStatement ps=con.prepareStatement("update tbl_idemployee set idDocument=? where empId=?");
                ps.setBinaryStream(1,finID,lenID);
                ps.setInt(2,empId);
                int i=ps.executeUpdate();
                if(i!=0)
                {
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane,"Error");
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,e);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        CurrentWorkingDirectory CWD=new CurrentWorkingDirectory();
        String path=CWD.getpath();
        HashMap para=new HashMap();
        para.put("empId",empId);
        ReportView re=new ReportView(path.concat("\\lib\\Reports\\Anar\\Employee\\Passport\\employeePassport.jasper"),para);
        re.setVisible(true);
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblPassport;
    // End of variables declaration//GEN-END:variables
    byte[] IDByte;
    BufferedImage bfImage,resizedImage;
    ImageIcon imageIcon;
    int empId,lenID;
    String pathID;
    File fileID;
    FileInputStream finID;
    JFileChooser fc=new JFileChooser(new File("Desktop"));
    Point middle = new Point(0,0);
}
